version: '3.7'
services:
  bazo-miner:
    container_name: bazo-miner
    build: ../bazo-miner/.
    volumes:
      - ../bazo-miner:/go/src/bazo-miner/
    expose:
      - "8000"
    networks:
      - bazo

  bazo-client:
    container_name: bazo-client
    build:
      context: ../ # We need the miner context as well when we build the client.
      dockerfile: bazo-client/Dockerfile # Dockerfile is relative to 'context' set inabove (!!!)
    depends_on: 
      - bazo-miner
    volumes:
      - ../bazo-client:/go/src/bazo-client/
      - ../bazo-miner:/go/src/bazo-miner/
    ports:
      - "80:8010"
    networks:
      - bazo

  bazo-block-explorer:
    container_name: bazo-block-explorer
    build:
      context: ../ # We need the miner context as well when we build the explorer.
      dockerfile: bazo-block-explorer/Dockerfile # Dockerfile is relative to 'context' set inabove (!!!)
    depends_on:
      - psql
      - bazo-miner
      - bazo-client
    volumes:
      - ../bazo-block-explorer:/go/src/bazo-block-explorer/
      - ../bazo-miner:/go/src/bazo-miner/
    ports:
      - "8080:8080"
    networks:
      - bazo
    restart: on-failure # This is necessary because postgres is not ready yet... Although we specified psql in depends_on

  psql:
    container_name: psql
    image: postgres
    environment:
      POSTGRES_DB: blockexplorerdb
      POSTGRES_USER: bazo
      POSTGRES_PASSWORD: bazo
    ports:
      - "5432:5432"
    networks:
      - bazo

networks:
  bazo: